### ISSUE TITLE
ELEMENT: Switch using Bootstrap

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#11]
## Create a react component for Switch using Bootstrap. 
**Note**: Commit only single file as per structure mentioned in readme

##  Information
- **Element Type:** Switch using Bootstrap
- **Framework:**
   - [x] Bootstrap
   - [ ] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by AW-STRAKH** [comment]
Hi ,
Can u please assign this issue as well to me if its fine.

Thanks

**Comment by iam-abbas** [comment]
> Hi , Can u please assign this issue as well to me if its fine.
> 
> Thanks

Go ahead!
