### ISSUE TITLE
ELEMENT: Switch using Tailwind

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#12]
## Create a react component for Switch using Tailwind. 
**Note**: Commit only single file as per structure mentioned in readme

##  Information
- **Element Type:** Switch using Tailwind
- **Framework:**
   - [ ] Bootstrap
   - [x] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by RShalman** [comment]
@iam-abbas If you wouldn't mind, I'd like to take this one also)

**Comment by iam-abbas** [comment]
> @iam-abbas If you wouldn't mind, I'd like to take this one also)
> 
> In tailwind)

Assigned
