### ISSUE TITLE
ELEMENT: Pricing using Tailwind

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#2]
## Create a react component for pricing section using tailwind. 
**Note**: Commit only single file as per structure mentioned in readme

##  Information
- **Element Type:** Pricing using Tailwind
- **Framework:**
   - [ ] Bootstrap
   - [x] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by fuadnafiz98** [comment]
Hello @iam-abbas, Can I work on this issue?

**Comment by iam-abbas** [comment]
@fuadnafiz98 go ahead!

**Comment by fuadnafiz98** [comment]
I've made a pull request. Would you please review my code?
