### ISSUE TITLE
Create JSX component of Switch using Tailwind or Bootstrap

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#21]
Create JSX component of Switch using Tailwind or Bootstrap. First create an issue using the given template and follow guidelines on Readme

**Comment by dev-autodidacta** [comment]
Hi, I would like to contribute to this, Please assign this issue to me.

**Comment by iam-abbas** [comment]
> Hi, I would like to contribute to this, Please assign this issue to me.

Go ahead and create an issue!
