### ISSUE TITLE
ELEMENT: Newsletter using Tailwind

### ISSUE THREAD

**Issue by GeoBrodas** [iam-abbas/React-Community-Elements#25]
# React Elements
- [x] This Element/Component is not available in the repository currently.
- [x] If it is, My Element is styled differently.
- [x] I am only committing single file as per the norm mentioned in readme.

##  Information

- **Newsletter** 
- **Framework:**
   - [ ] Bootstrap
   - [x] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by iam-abbas** [comment]
@GeoBrodas would you like to take this?

**Comment by GeoBrodas** [comment]
I made a pull request

**Comment by iam-abbas** [comment]
Perfect! Thank you!
