### ISSUE TITLE
ELEMENT:  DarkModeSwitch

### ISSUE THREAD

**Issue by iamshm** [iam-abbas/React-Community-Elements#27]
# React Elements
- [x] This Element/Component is not available in the repository currently.
- [ ] If it is, My Element is styled differently.
- [x] I am only committing single file as per the norm mentioned in readme.

##  Information

- **Element Type : Toggle Button** 
- **Framework:**
   - [x] StyledComponents
   - [ ] Bootstrap
   - [ ] Tailwind
   - [ ] None

**Comment by iam-abbas** [comment]
#28
