### ISSUE TITLE
ELEMENT: Sidebar using Bootstrap

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#3]
## Create a react component for Sidebar using Bootstrap. 
**Note**: Commit only single file as per structure mentioned in readme

##  Information
- **Element Type:** Sidebar using Bootstrap
- **Framework:**
   - [x] Bootstrap
   - [ ] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by AW-STRAKH** [comment]
Hi ,
Can you please assign this issue to me 

Thanks

**Comment by iam-abbas** [comment]
> Hi , Can you please assign this issue to me
> 
> Thanks

Assigned
