### ISSUE TITLE
ELEMENT: Hero section using Bootstrap

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#5]
## Create a react component for Hero section using Bootstrap. 
**Note**: Commit only single file as per structure mentioned in readme

##  Information
- **Element Type:** Hero section using Bootstrap
- **Framework:**
   - [x] Bootstrap
   - [ ] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by jawariaalvi32** [comment]
Hey @iam-abbas please assign me this. I want to work on it.

**Comment by iam-abbas** [comment]
Done @jawariaalvi32

**Comment by jawariaalvi32** [comment]
Created a PR. @iam-abbas please review.
