### ISSUE TITLE
ELEMENT: Accordion using Bootstrap

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#7]
## Create a react component for Accordion using Bootstrap. 
**Note**: Commit only single file as per structure mentioned in readme

##  Information
- **Element Type:** Accordion using Bootstrap
- **Framework:**
   - [x] Bootstrap
   - [ ] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by PranavTrip** [comment]
Hey @iam-abbas please assign this to me

**Comment by iam-abbas** [comment]
@PranavTrip assigned!

**Comment by PranavTrip** [comment]
> @PranavTrip assigned!

I just need to create an Accordion Component using React and Bootstrap. Right?

**Comment by iam-abbas** [comment]
> > @PranavTrip assigned!
> 
> I just need to create an Accordion Component using React and Bootstrap. Right?

Yes! and commit single js file (of accordion) to `Accordion/Bootstrap/<Custom Name>.js`. An example for <Custom Name> is "SimpleAccordion.js"
