### ISSUE TITLE
ELEMENT: Alert using Bootstrap

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#8]
## Create a react component for Alert using Bootstrap. 
**Note**: Commit only single file as per structure mentioned in readme

##  Information
- **Element Type:** Alert using Bootstrap
- **Framework:**
   - [x] Bootstrap
   - [ ] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by Raghav-Modani** [comment]
Hii , I would like to work on this, please assign me this issue.

**Comment by iam-abbas** [comment]
> Hii , I would like to work on this, please assign me this issue.

Assigned
