### ISSUE TITLE
ELEMENT: Alert using Tailwind

### ISSUE THREAD

**Issue by iam-abbas** [iam-abbas/React-Community-Elements#9]
## Create a react component for Alert using Tailwind.
**Note**: Commit only single file as per structure mentioned in readme

##  Information
- **Element Type:** Alert using Tailwind
- **Framework:**
   - [ ] Bootstrap
   - [x] Tailwind
   - [ ] None
   - [ ] Other (Specify)

**Comment by MrDoomy** [comment]
Hi 👋
I'd like to make my contribution as part of Hacktoberfest'21
Can you assign this issue to me?

**Comment by iam-abbas** [comment]
@MrDoomy Sure! Assigned!
